# Generated by Django 2.2.1 on 2019-05-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dripndry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'MONDAY'), ('Tue', 'TUESDAY'), ('Wed', 'WEDNESDAY'), ('Thu', 'THURSDAY'), ('Fri', 'FRIDAY'), ('Sat', 'SATURDAY')], default='MONDAY', max_length=50)),
                ('slot', models.CharField(choices=[('8.00AM-10.00AM', '8.00AM-10.00AM'), ('10.00AM-12.00PM', '10.00AM-12.00PM'), ('1.00PM-3.00PM', '1.00PM-3.00PM'), ('3.00PM-5.00PM', '3.00PM-5.00PM'), ('5.00PM-7.00PM', '5.00PM-7.00PM')], default='5.00PM-7.00PM', max_length=50)),
                ('urgent', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=50)),
                ('cloth', models.CharField(choices=[('Top', 'Tops'), ('Shirt', 'Shirts'), ('Trouser', 'Trousers'), ('Dress', 'Dresses'), ('Sarees', 'Sarees'), ('Baby', 'Baby items'), ('Suit', 'Suits/Jackets'), ('Sock', 'Socks/Gloves'), ('Bed', 'BedSheets'), ('Curtain', 'Curtains'), ('Other', 'Others')], default='Dress', max_length=50)),
                ('quantity', models.CharField(max_length=10)),
                ('treatment', models.CharField(choices=[('Wash and Fold', 'Wash and Fold'), ('Wash and Iron', 'Wash and Iron'), ('Dry Cleaning', 'Dry Cleaning')], default='Wash and Fold', max_length=50)),
            ],
        ),
    ]
