# Generated by Django 2.2.1 on 2019-05-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dripndry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='urgent',
            new_name='immediate_delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='day',
            new_name='pickup_day',
        ),
    ]
